### ISSUE TITLE
Should our meta fields be "namespaced" and/or not start with underscores?

### ISSUE THREAD

**Issue by davidbhayes** [roadwarriorwp/fcwp-testimonials#2]
Thinking that this doesn't super matter, but @mikeselander if you're doing small code style tweaks I'm curious about the way we're naming meta. What we've got for the extended meta fields are `_reviewertitle`, `_testimoniallink`, `_company`. We may either want to add the prefix to them and/or rename them possibly without the underscores (there has been a lot of noise around the latter issue with the WP-API but I've not really listened close enough to know the direction).

**Comment by mikeselander** [comment]
I think prefixing would be a better standard to set. Even if it's a simple `fcwp_` prefix on them it might help avoid collisions and make it easier to find in the db.

As for the REST API I wouldn't worry about it much either way - they just stuffed the post meta endpoint into a feature plugin so I wouldn't expect it to hit core for 2-3 more releases. I believe the problem lies with a `_` prefix cmb value being considered "private" and the meta API won't read those. I kinda feel like you should be putting meta in with a cpt or post endpoint though.

**Comment by mikeselander** [comment]
By the way, your commits are intensely granular! I'm impressed.

**Comment by amberhinds** [comment]
@davidbhayes To be honest I'm not sure why I did it that way.  Probably way back when when I first was learning how to add meta fields I googled it and found a tutorial that did it that way and thus it was how I "learned" to do it.  We can change it if it would be better.

**Comment by amberhinds** [comment]
I added a prefix to everything.  Pushing changes soon.
